import { readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),failures=[]; const read=r=>readFileSync(join(root,r),'utf8'); const ok=r=>{try{statSync(join(root,r));return true}catch{return false}}; const fail=m=>failures.push(m);
const m=JSON.parse(read('component-manifest.json')),p=JSON.parse(read('package.json')),content=read('assets/catalog-content.js'),registry=read('assets/components/index.js');
if(m.schemaVersion!==1) fail(`schemaVersion must be 1, found ${m.schemaVersion}.`); if(m.product?.version!==p.version) fail(`manifest version ${m.product?.version} does not match package version ${p.version}.`);
for(const s of ['start','build','preview','serve:test','validate','test:browser','test']) if(!p.scripts?.[s]) fail(`Missing script ${s}.`);
const compDocs=readdirSync(join(root,'components')).filter(x=>x.endsWith('.md')).length,foundDocs=readdirSync(join(root,'foundations')).filter(x=>x.endsWith('.md')).length;
if(m.components.length!==compDocs) fail(`Manifest declares ${m.components.length} components but ${compDocs} docs exist.`); if(m.foundations.length!==foundDocs) fail(`Manifest declares ${m.foundations.length} foundations but ${foundDocs} docs exist.`); if(m.components.length<10) fail('Need at least 10 components.');
for(const f of ['index.html','preview.html','404.html','assets/foundations.css','assets/docs.css','assets/catalog.js','assets/preview.js']) if(!ok(f)) fail(`Missing ${f}.`);
for(const f of m.foundations){ if(!ok(f.docPath)) fail(`Missing ${f.docPath}.`); if(!f.highlights?.length) fail(`${f.id} needs highlights.`); if(!content.includes(`case '${f.id}'`)) fail(`No foundation demo for ${f.id}.`)}
const seen=new Set();
for(const c of m.components){ if(seen.has(c.id)) fail(`Duplicate component id ${c.id}.`); seen.add(c.id); if(!ok(c.docPath)) fail(`Missing ${c.docPath}.`); if(!ok(c.source)) fail(`Missing ${c.source}.`); if(!c.examples?.length) fail(`${c.id} needs an example.`); if(!content.includes(`case '${c.id}'`)) fail(`No component demo for ${c.id}.`); if(c.implementation==='custom-element'){ if(!registry.includes(c.source.split('/').pop())) fail(`Registry missing ${c.source}.`); const src=read(c.source); const attrs=[...src.matchAll(/observedAttributes\(\)\{return\[([^\]]*)\]/g)].flatMap(m=>[...m[1].matchAll(/'([^']+)'/g)].map(x=>x[1])); const docs=new Set(c.attributes.map(a=>a.name)); for(const a of attrs) if(!docs.has(a)) fail(`${c.id} observes undocumented attribute ${a}.`); if(!src.includes('customElements.define')) fail(`${c.source} never defines a custom element.`);} }
if(failures.length){ console.error(`Design-system validation failed with ${failures.length} problem${failures.length===1?'':'s'}:`); for(const f of failures) console.error(`  - ${f}`); process.exit(1);} console.log(`Validated RTR design-system manifest v${m.product.version}: ${m.foundations.length} foundations and ${m.components.length} components.`);
